// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr-KF959uioTSKKqeD2F-5mXz6ExB9YUM',
    appId: '1:1087044718680:android:9f520857a679dc6e1c7a2d',
    messagingSenderId: '1087044718680',
    projectId: 'swiftclean-a6aa1',
    databaseURL: 'https://swiftclean-a6aa1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swiftclean-a6aa1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNfAVvpkQLxu5ehZDiTCiqtDHRaAGhZe0',
    appId: '1:1087044718680:ios:a0a7ad41b3b8e8d81c7a2d',
    messagingSenderId: '1087044718680',
    projectId: 'swiftclean-a6aa1',
    databaseURL: 'https://swiftclean-a6aa1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'swiftclean-a6aa1.firebasestorage.app',
    iosBundleId: 'com.example.testingFirebase',
  );
}
